package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// Metric names constants
const (
	MetricVPINCurrent                 = "mm_vpin_current"
	MetricVolatilityRegime            = "mm_volatility_regime"
	MetricAdverseSelectionRate        = "mm_adverse_selection_rate"
	MetricInventoryNet                = "mm_inventory_net"
	MetricReservationPrice            = "mm_reservation_price"
	MetricInventorySkewBps            = "mm_inventory_skew_bps"
	MetricAdaptiveNetMax              = "mm_adaptive_netmax"
	MetricSpreadGauge                 = "mm_spread_gauge"
	MetricQuoteIntervalGauge          = "mm_quote_interval_gauge"
	MetricQuotesGeneratedTotal        = "mm_quotes_generated_total"
	MetricOrdersPlacedTotal           = "mm_orders_placed_total"
	MetricFillsTotal                  = "mm_fills_total"
	MetricRestRequestsTotal           = "mm_rest_requests_total"
	MetricRestErrorsTotal             = "mm_rest_errors_total"
	MetricRestLatencySeconds          = "mm_rest_latency_seconds"
	MetricGatewayOrdersPlacedTotal    = "mm_gateway_orders_placed_total"
	MetricDynamicOrderUpdatesTotal    = "mm_dynamic_order_updates_total"
	MetricDynamicOrderCancelsTotal    = "mm_dynamic_order_cancels_total"
	MetricPostOnlyUsageTotal          = "mm_postonly_usage_total"
	MetricPostOnlyRejectFallbackTotal = "mm_postonly_reject_fallback_total"
	MetricFillRateCurrent             = "mm_fill_rate_current"
	MetricRecentFillsCount            = "mm_recent_fills_count"
	MetricCancelSuppressionActive     = "mm_cancel_suppression_active"
)

var (
	// VPINCurrent 当前VPIN值
	VPINCurrent = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricVPINCurrent,
		Help: "Current VPIN value",
	})

	// VolatilityRegime 市场波动状态
	VolatilityRegime = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricVolatilityRegime,
		Help: "Market regime based on volatility (0=Calm, 1=TrendUp, 2=TrendDown, 3=HighVol)",
	})

	// AdverseSelectionRate 逆向选择率
	AdverseSelectionRate = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricAdverseSelectionRate,
		Help: "Adverse selection rate",
	})

	// InventoryNet 净仓位
	InventoryNet = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricInventoryNet,
		Help: "Net inventory position",
	})

	// ReservationPrice 预订价格
	ReservationPrice = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricReservationPrice,
		Help: "Reservation price calculated by the strategy",
	})

	// InventorySkewBps 仓位偏移基点
	InventorySkewBps = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricInventorySkewBps,
		Help: "Inventory skew in basis points",
	})

	// AdaptiveNetMax 自适应最大净仓位
	AdaptiveNetMax = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricAdaptiveNetMax,
		Help: "Adaptive net position limit",
	})

	// SpreadGauge 点差
	SpreadGauge = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: MetricSpreadGauge,
		Help: "Current spread",
	}, []string{"symbol"})

	// QuoteIntervalGauge 报价间隔
	QuoteIntervalGauge = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: MetricQuoteIntervalGauge,
		Help: "Quote interval in seconds",
	}, []string{"symbol"})

	// StrategyQuotesGenerated 策略生成的报价数量
	StrategyQuotesGenerated = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricQuotesGeneratedTotal,
		Help: "Total number of quotes generated by strategy",
	}, []string{"side"})

	// StrategyOrdersPlaced 策略下单数量
	StrategyOrdersPlaced = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricOrdersPlacedTotal,
		Help: "Total number of orders placed by strategy",
	}, []string{"side"})

	// StrategyFills 策略成交数量
	StrategyFills = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricFillsTotal,
		Help: "Total number of fills received by strategy",
	}, []string{"side"})

	// RestRequestsCounter REST请求数量
	RestRequestsCounter = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricRestRequestsTotal,
		Help: "Total number of REST requests",
	}, []string{"method", "symbol"})

	// RestErrorsCounter REST错误数量
	RestErrorsCounter = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricRestErrorsTotal,
		Help: "Total number of REST errors",
	}, []string{"method", "symbol"})

	// RestLatencyHistogram REST延迟直方图
	RestLatencyHistogram = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name: MetricRestLatencySeconds,
		Help: "REST request latency in seconds",
	}, []string{"method", "symbol"})

	// OrdersPlacedCounter 下单数量
	OrdersPlacedCounter = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricGatewayOrdersPlacedTotal,
		Help: "Total number of orders placed",
	}, []string{"symbol"})

	// FillRateCurrent 当前成交率（每分钟成交次数）
	FillRateCurrent = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricFillRateCurrent,
		Help: "Current fill rate (fills per minute)",
	})

	// RecentFillsCount 近期成交次数
	RecentFillsCount = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricRecentFillsCount,
		Help: "Recent fills count in the tracking window",
	})

	// CancelSuppressionActive 撤单抑制是否激活
	CancelSuppressionActive = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricCancelSuppressionActive,
		Help: "Cancel suppression active (1=active, 0=inactive)",
	})
)

// Dynamic metrics for multi-level
var (
	DynamicOrderUpdates = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricDynamicOrderUpdatesTotal,
		Help: "Total dynamic order updates (placements)",
	}, []string{"side"})
	DynamicOrderCancels = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricDynamicOrderCancelsTotal,
		Help: "Total dynamic order cancels",
	}, []string{"side"})
	PostOnlyUsage = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricPostOnlyUsageTotal,
		Help: "Total post-only usage",
	}, []string{"side"})
	PostOnlyRejectFallback = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricPostOnlyRejectFallbackTotal,
		Help: "Total post-only rejects that triggered fallback",
	}, []string{"side"})
)

// UpdateMarketMetrics 更新市场相关指标
func UpdateMarketMetrics(vpin float64, regime int, inventoryNet float64) {
	VPINCurrent.Set(vpin)
	VolatilityRegime.Set(float64(regime))
	InventoryNet.Set(inventoryNet)
}

// UpdateStrategyMetrics 更新策略相关指标
func UpdateStrategyMetrics(reservationPrice float64, inventorySkewBps float64, adaptiveNetMax float64) {
	ReservationPrice.Set(reservationPrice)
	InventorySkewBps.Set(inventorySkewBps)
	AdaptiveNetMax.Set(adaptiveNetMax)
}

// UpdatePostTradeMetrics 更新事后交易指标
func UpdatePostTradeMetrics(adverseSelectionRate float64) {
	AdverseSelectionRate.Set(adverseSelectionRate)
}

// IncrementQuotesGenerated 增加生成报价计数
func IncrementQuotesGenerated(side string) {
	StrategyQuotesGenerated.WithLabelValues(side).Inc()
}

// IncrementOrdersPlaced 增加下单计数
func IncrementOrdersPlaced(side string) {
	StrategyOrdersPlaced.WithLabelValues(side).Inc()
}

// IncrementFills 增加成交计数
func IncrementFills(side string) {
	StrategyFills.WithLabelValues(side).Inc()
}

// Dynamic metrics increment helpers
func IncrementDynamicOrderUpdate(side string) {
	DynamicOrderUpdates.WithLabelValues(side).Inc()
}
func IncrementDynamicOrderCancel(side string) {
	DynamicOrderCancels.WithLabelValues(side).Inc()
}
func IncrementPostOnlyUsage(side string) {
	PostOnlyUsage.WithLabelValues(side).Inc()
}
func IncrementPostOnlyRejectFallback(side string) {
	PostOnlyRejectFallback.WithLabelValues(side).Inc()
}

// UpdateFillTrackerMetrics 更新成交跟踪指标
func UpdateFillTrackerMetrics(fillRate float64, recentFills int, suppressionActive bool) {
	FillRateCurrent.Set(fillRate)
	RecentFillsCount.Set(float64(recentFills))
	if suppressionActive {
		CancelSuppressionActive.Set(1)
	} else {
		CancelSuppressionActive.Set(0)
	}
}

// 核心运行时指标
var (
	// MidPrice 中间价
	MidPrice = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "mm_mid_price",
		Help: "Current mid price",
	}, []string{"symbol"})

	// BidPrice 买一价
	BidPrice = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "mm_bid_price",
		Help: "Current best bid price",
	}, []string{"symbol"})

	// AskPrice 卖一价
	AskPrice = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "mm_ask_price",
		Help: "Current best ask price",
	}, []string{"symbol"})

	// Position 当前仓位
	Position = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "mm_position",
		Help: "Current net position",
	}, []string{"symbol"})

	// EntryPrice 持仓均价
	EntryPrice = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "mm_entry_price",
		Help: "Average entry price",
	}, []string{"symbol"})

	// UnrealizedPnL 未实现盈亏
	UnrealizedPnL = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "mm_unrealized_pnl",
		Help: "Unrealized PnL in USD",
	}, []string{"symbol"})

	// RealizedPnL 已实现盈亏
	RealizedPnL = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "mm_realized_pnl",
		Help: "Realized PnL in USD",
	}, []string{"symbol"})

	// ActiveOrders 活跃订单数
	ActiveOrders = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "mm_active_orders",
		Help: "Number of active orders",
	}, []string{"symbol", "side"})

	// TotalFills 总成交次数
	TotalFills = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "mm_total_fills",
		Help: "Total number of fills",
	}, []string{"symbol", "side"})

	// OrdersPlaced 下单次数
	OrdersPlaced = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "mm_orders_placed_count",
		Help: "Total orders placed",
	}, []string{"symbol", "side"})

	// OrdersCanceled 撤单次数
	OrdersCanceled = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "mm_orders_canceled_count",
		Help: "Total orders canceled",
	}, []string{"symbol"})
)

// Round8 Survival 新增指标
var (
	WorstCaseLong = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_worst_case_long",
		Help: "Worst-case long exposure",
	})
	WorstCaseShort = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_worst_case_short",
		Help: "Worst-case short exposure",
	})
	DynamicDecayFactor = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_dynamic_decay_factor",
		Help: "Current size decay factor",
	})
	FundingPnlAccum = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_funding_pnl_acc",
		Help: "Accumulated funding PnL",
	})
	PredictedFundingRate = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_predicted_funding_rate",
		Help: "Predicted next funding rate",
	})
	GrindCountTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "mm_grind_count_total",
		Help: "Total grind executions",
	})
	GrindActive = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_grind_active",
		Help: "Grinding active (1=active, 0=inactive)",
	})
	GrindCostSaved = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_grind_cost_saved",
		Help: "Estimated cost saved by grinding",
	})
	PriceStdDev30m = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_price_stddev_30m",
		Help: "30-minute price standard deviation",
	})
	QuoteSuppressed = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_quote_suppressed",
		Help: "Quote suppressed due to worst-case (1=yes, 0=no)",
	})
	WSConnected = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_ws_connected",
		Help: "WebSocket connection status (1=connected, 0=disconnected)",
	})
	RestFallbackCount = promauto.NewCounter(prometheus.CounterOpts{
		Name: "mm_rest_fallback_count",
		Help: "REST fallback usage count",
	})
	PendingExposure = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "mm_pending_exposure",
		Help: "Pending order quantity grouped by side",
	}, []string{"symbol", "side"})
	RunnerRiskState = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "mm_runner_risk_state",
		Help: "Runner risk state (0=normal,1=soft reduce,2=hard reduce)",
	}, []string{"symbol"})
	ReduceOnlyForceCount = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "mm_reduce_only_force_total",
		Help: "Reduce-only forced market actions",
	}, []string{"symbol"})

	PinningActive = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_pinning_active",
		Help: "Pinning mode active (1=active, 0=inactive)",
	})
	FarQuotesCount = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_far_quotes_count",
		Help: "Number of far quotes placed",
	})
	QuoteFlickerRate = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_quote_flicker_rate",
		Help: "Quote flicker rate per minute",
	})
	FillRate5m = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_fill_rate_5m",
		Help: "Fill rate over last 5 minutes",
	})
)

// UpdateMarketData 更新市场数据指标
func UpdateMarketData(symbol string, mid, bid, ask float64) {
	if mid > 0 {
		MidPrice.WithLabelValues(symbol).Set(mid)
	}
	if bid > 0 {
		BidPrice.WithLabelValues(symbol).Set(bid)
	}
	if ask > 0 {
		AskPrice.WithLabelValues(symbol).Set(ask)
	}
}

// UpdatePositionMetrics 更新仓位指标
func UpdatePositionMetrics(symbol string, position, entryPrice, unrealizedPnL, realizedPnL float64) {
	Position.WithLabelValues(symbol).Set(position)
	if entryPrice > 0 {
		EntryPrice.WithLabelValues(symbol).Set(entryPrice)
	}
	UnrealizedPnL.WithLabelValues(symbol).Set(unrealizedPnL)
	RealizedPnL.WithLabelValues(symbol).Set(realizedPnL)
}

// UpdateOrderMetrics 更新订单指标
func UpdateOrderMetrics(symbol string, activeBids, activeAsks int) {
	ActiveOrders.WithLabelValues(symbol, "buy").Set(float64(activeBids))
	ActiveOrders.WithLabelValues(symbol, "sell").Set(float64(activeAsks))
}

// UpdatePendingExposure 更新挂单敞口
func UpdatePendingExposure(symbol string, pendingBuy, pendingSell float64) {
	PendingExposure.WithLabelValues(symbol, "buy").Set(pendingBuy)
	PendingExposure.WithLabelValues(symbol, "sell").Set(pendingSell)
}

// IncrementFill 成交计数
func IncrementFill(symbol, side string) {
	TotalFills.WithLabelValues(symbol, side).Inc()
}

// IncrementOrderPlaced 下单计数
func IncrementOrderPlaced(symbol, side string) {
	OrdersPlaced.WithLabelValues(symbol, side).Inc()
}

// IncrementOrderCanceled 撤单计数
func IncrementOrderCanceled(symbol string) {
	OrdersCanceled.WithLabelValues(symbol).Inc()
}
