package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// Metric names constants
const (
	MetricVPINCurrent                 = "mm_vpin_current"
	MetricVolatilityRegime            = "mm_volatility_regime"
	MetricAdverseSelectionRate        = "mm_adverse_selection_rate"
	MetricInventoryNet                = "mm_inventory_net"
	MetricReservationPrice            = "mm_reservation_price"
	MetricInventorySkewBps            = "mm_inventory_skew_bps"
	MetricAdaptiveNetMax              = "mm_adaptive_netmax"
	MetricSpreadGauge                 = "mm_spread_gauge"
	MetricQuoteIntervalGauge          = "mm_quote_interval_gauge"
	MetricQuotesGeneratedTotal        = "mm_quotes_generated_total"
	MetricOrdersPlacedTotal           = "mm_orders_placed_total"
	MetricFillsTotal                  = "mm_fills_total"
	MetricRestRequestsTotal           = "mm_rest_requests_total"
	MetricRestErrorsTotal             = "mm_rest_errors_total"
	MetricRestLatencySeconds          = "mm_rest_latency_seconds"
	MetricGatewayOrdersPlacedTotal    = "mm_gateway_orders_placed_total"
	MetricDynamicOrderUpdatesTotal    = "mm_dynamic_order_updates_total"
	MetricDynamicOrderCancelsTotal    = "mm_dynamic_order_cancels_total"
	MetricPostOnlyUsageTotal          = "mm_postonly_usage_total"
	MetricPostOnlyRejectFallbackTotal = "mm_postonly_reject_fallback_total"
	MetricFillRateCurrent             = "mm_fill_rate_current"
	MetricRecentFillsCount            = "mm_recent_fills_count"
	MetricCancelSuppressionActive     = "mm_cancel_suppression_active"
)

var (
	// VPINCurrent 当前VPIN值
	VPINCurrent = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricVPINCurrent,
		Help: "Current VPIN value",
	})

	// VolatilityRegime 市场波动状态
	VolatilityRegime = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricVolatilityRegime,
		Help: "Market regime based on volatility (0=Calm, 1=TrendUp, 2=TrendDown, 3=HighVol)",
	})

	// AdverseSelectionRate 逆向选择率
	AdverseSelectionRate = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricAdverseSelectionRate,
		Help: "Adverse selection rate",
	})

	// InventoryNet 净仓位
	InventoryNet = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricInventoryNet,
		Help: "Net inventory position",
	})

	// ReservationPrice 预订价格
	ReservationPrice = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricReservationPrice,
		Help: "Reservation price calculated by the strategy",
	})

	// InventorySkewBps 仓位偏移基点
	InventorySkewBps = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricInventorySkewBps,
		Help: "Inventory skew in basis points",
	})

	// AdaptiveNetMax 自适应最大净仓位
	AdaptiveNetMax = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricAdaptiveNetMax,
		Help: "Adaptive net position limit",
	})

	// SpreadGauge 点差
	SpreadGauge = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: MetricSpreadGauge,
		Help: "Current spread",
	}, []string{"symbol"})

	// QuoteIntervalGauge 报价间隔
	QuoteIntervalGauge = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: MetricQuoteIntervalGauge,
		Help: "Quote interval in seconds",
	}, []string{"symbol"})

	// StrategyQuotesGenerated 策略生成的报价数量
	StrategyQuotesGenerated = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricQuotesGeneratedTotal,
		Help: "Total number of quotes generated by strategy",
	}, []string{"side"})

	// StrategyOrdersPlaced 策略下单数量
	StrategyOrdersPlaced = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricOrdersPlacedTotal,
		Help: "Total number of orders placed by strategy",
	}, []string{"side"})

	// StrategyFills 策略成交数量
	StrategyFills = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricFillsTotal,
		Help: "Total number of fills received by strategy",
	}, []string{"side"})

	// RestRequestsCounter REST请求数量
	RestRequestsCounter = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricRestRequestsTotal,
		Help: "Total number of REST requests",
	}, []string{"method", "symbol"})

	// RestErrorsCounter REST错误数量
	RestErrorsCounter = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricRestErrorsTotal,
		Help: "Total number of REST errors",
	}, []string{"method", "symbol"})

	// RestLatencyHistogram REST延迟直方图
	RestLatencyHistogram = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name: MetricRestLatencySeconds,
		Help: "REST request latency in seconds",
	}, []string{"method", "symbol"})

	// OrdersPlacedCounter 下单数量
	OrdersPlacedCounter = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricGatewayOrdersPlacedTotal,
		Help: "Total number of orders placed",
	}, []string{"symbol"})

	// FillRateCurrent 当前成交率（每分钟成交次数）
	FillRateCurrent = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricFillRateCurrent,
		Help: "Current fill rate (fills per minute)",
	})

	// RecentFillsCount 近期成交次数
	RecentFillsCount = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricRecentFillsCount,
		Help: "Recent fills count in the tracking window",
	})

	// CancelSuppressionActive 撤单抑制是否激活
	CancelSuppressionActive = promauto.NewGauge(prometheus.GaugeOpts{
		Name: MetricCancelSuppressionActive,
		Help: "Cancel suppression active (1=active, 0=inactive)",
	})
)

// Dynamic metrics for multi-level
var (
	DynamicOrderUpdates = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricDynamicOrderUpdatesTotal,
		Help: "Total dynamic order updates (placements)",
	}, []string{"side"})
	DynamicOrderCancels = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricDynamicOrderCancelsTotal,
		Help: "Total dynamic order cancels",
	}, []string{"side"})
	PostOnlyUsage = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricPostOnlyUsageTotal,
		Help: "Total post-only usage",
	}, []string{"side"})
	PostOnlyRejectFallback = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: MetricPostOnlyRejectFallbackTotal,
		Help: "Total post-only rejects that triggered fallback",
	}, []string{"side"})
)

// UpdateMarketMetrics 更新市场相关指标
func UpdateMarketMetrics(vpin float64, regime int, inventoryNet float64) {
	VPINCurrent.Set(vpin)
	VolatilityRegime.Set(float64(regime))
	InventoryNet.Set(inventoryNet)
}

// UpdateStrategyMetrics 更新策略相关指标
func UpdateStrategyMetrics(reservationPrice float64, inventorySkewBps float64, adaptiveNetMax float64) {
	ReservationPrice.Set(reservationPrice)
	InventorySkewBps.Set(inventorySkewBps)
	AdaptiveNetMax.Set(adaptiveNetMax)
}

// UpdatePostTradeMetrics 更新事后交易指标
func UpdatePostTradeMetrics(adverseSelectionRate float64) {
	AdverseSelectionRate.Set(adverseSelectionRate)
}

// IncrementQuotesGenerated 增加生成报价计数
func IncrementQuotesGenerated(side string) {
	StrategyQuotesGenerated.WithLabelValues(side).Inc()
}

// IncrementOrdersPlaced 增加下单计数
func IncrementOrdersPlaced(side string) {
	StrategyOrdersPlaced.WithLabelValues(side).Inc()
}

// IncrementFills 增加成交计数
func IncrementFills(side string) {
	StrategyFills.WithLabelValues(side).Inc()
}

// Dynamic metrics increment helpers
func IncrementDynamicOrderUpdate(side string) {
	DynamicOrderUpdates.WithLabelValues(side).Inc()
}
func IncrementDynamicOrderCancel(side string) {
	DynamicOrderCancels.WithLabelValues(side).Inc()
}
func IncrementPostOnlyUsage(side string) {
	PostOnlyUsage.WithLabelValues(side).Inc()
}
func IncrementPostOnlyRejectFallback(side string) {
	PostOnlyRejectFallback.WithLabelValues(side).Inc()
}

// UpdateFillTrackerMetrics 更新成交跟踪指标
func UpdateFillTrackerMetrics(fillRate float64, recentFills int, suppressionActive bool) {
	FillRateCurrent.Set(fillRate)
	RecentFillsCount.Set(float64(recentFills))
	if suppressionActive {
		CancelSuppressionActive.Set(1)
	} else {
		CancelSuppressionActive.Set(0)
	}
}
