package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	// VPINCurrent 当前VPIN值
	VPINCurrent = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_vpin_current",
		Help: "Current VPIN value",
	})

	// VolatilityRegime 市场波动状态
	VolatilityRegime = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_volatility_regime",
		Help: "Market regime based on volatility (0=Calm, 1=TrendUp, 2=TrendDown, 3=HighVol)",
	})

	// AdverseSelectionRate 逆向选择率
	AdverseSelectionRate = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_adverse_selection_rate",
		Help: "Adverse selection rate",
	})

	// InventoryNet 净仓位
	InventoryNet = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_inventory_net",
		Help: "Net inventory position",
	})

	// ReservationPrice 预订价格
	ReservationPrice = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_reservation_price",
		Help: "Reservation price calculated by the strategy",
	})

	// InventorySkewBps 仓位偏移基点
	InventorySkewBps = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_inventory_skew_bps",
		Help: "Inventory skew in basis points",
	})

	// AdaptiveNetMax 自适应最大净仓位
	AdaptiveNetMax = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "mm_adaptive_netmax",
		Help: "Adaptive net position limit",
	})

	// SpreadGauge 点差
	SpreadGauge = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "mm_spread_gauge",
		Help: "Current spread",
	}, []string{"symbol"})

	// QuoteIntervalGauge 报价间隔
	QuoteIntervalGauge = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "mm_quote_interval_gauge",
		Help: "Quote interval in seconds",
	}, []string{"symbol"})

	// StrategyQuotesGenerated 策略生成的报价数量
	StrategyQuotesGenerated = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "mm_quotes_generated_total",
		Help: "Total number of quotes generated by strategy",
	}, []string{"side"})

	// StrategyOrdersPlaced 策略下单数量
	StrategyOrdersPlaced = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "mm_orders_placed_total",
		Help: "Total number of orders placed by strategy",
	}, []string{"side"})

	// StrategyFills 策略成交数量
	StrategyFills = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "mm_fills_total",
		Help: "Total number of fills received by strategy",
	}, []string{"side"})

	// RestRequestsCounter REST请求数量
	RestRequestsCounter = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "mm_rest_requests_total",
		Help: "Total number of REST requests",
	}, []string{"method", "symbol"})

	// RestErrorsCounter REST错误数量
	RestErrorsCounter = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "mm_rest_errors_total",
		Help: "Total number of REST errors",
	}, []string{"method", "symbol"})

	// RestLatencyHistogram REST延迟直方图
	RestLatencyHistogram = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name: "mm_rest_latency_seconds",
		Help: "REST request latency in seconds",
	}, []string{"method", "symbol"})

	// OrdersPlacedCounter 下单数量
	OrdersPlacedCounter = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "mm_gateway_orders_placed_total",
		Help: "Total number of orders placed",
	}, []string{"symbol"})
)

// UpdateMarketMetrics 更新市场相关指标
func UpdateMarketMetrics(vpin float64, regime int, inventoryNet float64) {
	VPINCurrent.Set(vpin)
	VolatilityRegime.Set(float64(regime))
	InventoryNet.Set(inventoryNet)
}

// UpdateStrategyMetrics 更新策略相关指标
func UpdateStrategyMetrics(reservationPrice float64, inventorySkewBps float64, adaptiveNetMax float64) {
	ReservationPrice.Set(reservationPrice)
	InventorySkewBps.Set(inventorySkewBps)
	AdaptiveNetMax.Set(adaptiveNetMax)
}

// UpdatePostTradeMetrics 更新事后交易指标
func UpdatePostTradeMetrics(adverseSelectionRate float64) {
	AdverseSelectionRate.Set(adverseSelectionRate)
}

// IncrementQuotesGenerated 增加生成报价计数
func IncrementQuotesGenerated(side string) {
	StrategyQuotesGenerated.WithLabelValues(side).Inc()
}

// IncrementOrdersPlaced 增加下单计数
func IncrementOrdersPlaced(side string) {
	StrategyOrdersPlaced.WithLabelValues(side).Inc()
}

// IncrementFills 增加成交计数
func IncrementFills(side string) {
	StrategyFills.WithLabelValues(side).Inc()
}